#!/bin/bash

export CMD="java"
export SCRIPT_LOCATION=$(dirname $0)
cd ${SCRIPT_LOCATION}

[[ $1 == "-d" ]] && CMD="java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"

exec ${CMD} \
  -p lib/shared:framework \
  --add-modules ALL-MODULE-PATH \
  -cp .:lib/system/* \
  ir.moke.dena.MainClass
